# Use uma imagem oficial do Python como imagem base (ajuste a tag conforme necessário)
FROM python:3.8-slim

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o script para o contêiner
COPY sync-dags.sh .

# Instale o AWS CLI (necessário para interagir com o S3)
RUN pip install awscli

# Dê permissão de execução ao script
RUN chmod +x sync-dags.sh

# Comando a ser executado quando o contêiner iniciar
CMD ["/app/sync-dags.sh"]
################
FROM alpine:latest

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o script para o contêiner
COPY sync-dags.sh .

# Instale o AWS CLI e outras dependências (ajuste conforme necessário)
RUN apk --no-cache add python3 py3-pip && \
    pip3 install --upgrade pip && \
    pip3 install awscli && \
    chmod +x sync-dags.sh

# Comando a ser executado quando o contêiner iniciar
CMD ["/app/sync-dags.sh"]
